import { syncContent } from '../services/contentSyncService';

/**
 * "컨텐츠 업데이트해줘" 명령어 처리 헬퍼
 * Claude Code에서 사용자 요청을 받았을 때 실행되는 함수
 */
export const handleContentUpdateRequest = async () => {
  try {
    console.log('🎯 컨텐츠 업데이트 요청 처리 시작...');
    
    // 1. localStorage에서 필요한 파일 목록 확인 및 bash 명령어 생성
    const result = await syncContent();
    
    if (result.commands.length === 0) {
      console.log(result.summary);
      return {
        success: false,
        message: result.summary,
        commands: []
      };
    }
    
    console.log(result.summary);
    
    // 2. 생성된 bash 명령어들 반환 (Claude Code에서 실행)
    return {
      success: true,
      message: result.summary,
      commands: result.commands,
      instructions: [
        '🔄 다음 명령어들을 순차적으로 실행합니다:',
        '1. 파일 존재 확인 및 선택적 복사',
        '2. Git add, commit, push',
        '3. 완료 알림'
      ]
    };
    
  } catch (error) {
    console.error('❌ 컨텐츠 업데이트 처리 중 오류:', error);
    return {
      success: false,
      message: `❌ 오류 발생: ${error instanceof Error ? error.message : '알 수 없는 오류'}`,
      commands: []
    };
  }
};

/**
 * 사용자가 "컨텐츠 업데이트해줘", "컨텐츠 동기화해줘" 등의 명령어를 입력했는지 확인
 */
export const isContentUpdateCommand = (userMessage: string): boolean => {
  const contentUpdateKeywords = [
    '컨텐츠 업데이트',
    '컨텐츠 동기화',
    '컨텐츠 이미지 업데이트',
    '뉴스 파일 업데이트',
    '이미지 업데이트',
    '텍스트 업데이트',
    '파일 동기화'
  ];
  
  const message = userMessage.toLowerCase().replace(/\s/g, '');
  return contentUpdateKeywords.some(keyword => 
    message.includes(keyword.toLowerCase().replace(/\s/g, ''))
  );
};

/**
 * Git 커밋 메시지 생성
 */
export const generateCommitMessage = (fileCount: number): string => {
  const timestamp = new Date().toISOString().split('T')[0];
  return `Update news content files (${fileCount} files) - ${timestamp}

- Sync text and image files from contents/ to public/contents/
- Updated based on published articles in localStorage
- Auto-generated by content sync system

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>`;
};