import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const contentDir = path.join(__dirname, '../public/contents/01');
const outputFile = path.join(__dirname, '../src/data/contentData.js');

function generateContentModule() {
  const contentData = {};
  
  // Read all .txt files in the contents directory
  const files = fs.readdirSync(contentDir).filter(file => file.endsWith('.txt'));
  
  files.forEach(file => {
    const filePath = path.join(contentDir, file);
    const content = fs.readFileSync(filePath, 'utf-8');
    
    // Use filename as key (without .txt extension)
    const key = file.replace('.txt', '');
    contentData[key] = content;
  });
  
  // Generate the JavaScript module
  const moduleContent = `// Auto-generated content data
// DO NOT EDIT - This file is generated by scripts/generateContentModule.js

export const contentData = ${JSON.stringify(contentData, null, 2)};
`;

  // Create src/data directory if it doesn't exist
  const dataDir = path.dirname(outputFile);
  if (!fs.existsSync(dataDir)) {
    fs.mkdirSync(dataDir, { recursive: true });
  }
  
  // Write the module file
  fs.writeFileSync(outputFile, moduleContent);
  
  console.log(`Generated contentData.js with ${files.length} files`);
}

generateContentModule();